16:49:04: Вы пытаетесь аутентифицироваться в систуму.
16:49:04: У вас есть 3 попыток
16:49:11: Вы ввели некорректный символ
Traceback (most recent call last):
  File "C:\Users\halim\PycharmProjects\flaskProject\venv\SkillBox2\module_6\task_1\task_1.py", line 18, in input_and_check_password
    hasher.update(password.encode("latin-1"))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
16:49:18: Вы успешно вошли в систему.
16:49:35: Вы пытаетесь аутентифицироваться в систуму.
16:49:35: У вас есть 3 попыток
16:49:38: Пользователь трижды ввёл неправильный пароль!
16:49:57: Вы пытаетесь аутентифицироваться в систуму.
16:49:57: У вас есть 3 попыток
16:49:58: Вы ввели пустой пароль.
16:49:58: Вы ввели пустой пароль.
16:49:58: Вы ввели пустой пароль.
16:49:58: Пользователь трижды ввёл неправильный пароль!
